### ISSUE TITLE
Migration to discord.js

### ISSUE THREAD

**Issue by MirageAegis** [MirageAegis/Sushi-Bot#18]
# Task
This means that Sushi Bot will be translated to ~~JavaScript~~ TypeScript.\
All future development will be in ~~JavaScript~~ TypeScript and [discord.js](https://github.com/discordjs/discord.js)

## Task Definitions
- [x] Migrate all current commands to SushiBot.ts
  - [x] `ban`
  - [x] `credits`
  - [x] `help`
  - [x] `info`
  - [x] `kick`
  - [x] `ping`
  - [x] `status`
  - [x] `unban`
- [x] All commands MUST have help command embeds
- [x] The code should be well documented

**Additionally**
The repository will be reworked to increase consistency in the development process, and to make artifacts easier to digest
- [x] Update templates
- [x] Update existing issues to match the updated templates
- [x] Update past issues to match the updated templates
- [x] Update past PRs to match the updated templates

**Comment by MirageAegis** [comment]
All commands have been translated to TypeScript now. I'll update the repo templates before this issue is ready to be reviewed

**Comment by MirageAegis** [comment]
The repo's issues and PRs will now be updated

**Comment by MirageAegis** [comment]
The issues and PR have been updated, this issue is now ready to be reviewed
