### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by MirageAegis** [MirageAegis/Sushi-Bot#21]
# Task
Add contribution guidelines to this repository for consistent quality, and to ensure a safe community

## Task Definitions
- [x] Create `CONTRIBUTING.md` with contribution guidelines
  - [x] Must include issue guidelines
  - [x] Must include pull request guidelines
- [x] Create `COMMIT_CONVENTION.md`
- [x] Create `CODE_OF_CONDUCT.md`
